-- CREATE DATABASE SQL198
-- USE SQL198

-- 1. Display the number of states present in the LocationTable.
SELECT COUNT(DISTINCT State) AS NoOfStates 
FROM Location;

-- 2. How many products are of regular type?
SELECT COUNT(*) AS RegularProducts
FROM Product
WHERE Type = 'Regular';

-- 3. Total spending on marketing of product ID 1
SELECT SUM(Marketing) AS TotalMarketingSpend
FROM Fact
WHERE ProductID = 1;

-- 4. Minimum sales of a product
SELECT MIN(Sales) AS MinSales
FROM Fact;

-- 5. Maximum Cost of Goods Sold (COGS)
SELECT MAX(COGS) AS MaxCOGS 
FROM Fact;

-- 6. Details of products where product type is Coffee
SELECT *
FROM Product
WHERE Product_Type = 'Coffee';

-- 7. Details where total expenses > 40
SELECT *
FROM Fact
WHERE Total_Expenses > 40;

-- 8. Average sales in area code 719
SELECT AVG(Sales) AS AvgSales
FROM Fact
WHERE Area_Code = 719;

-- 9. Total profit generated by Colorado state
SELECT SUM(f.Profit) AS TotalProfit
FROM Fact f
JOIN Location l ON f.Area_Code = l.Area_Code
WHERE l.State = 'Colorado';

-- 10. Average inventory for each product ID
SELECT ProductID, AVG(Inventory) AS AvgInventory
FROM Fact
GROUP BY ProductID
ORDER BY ProductId;

-- 11. Display states in sequential (alphabetical) order
SELECT DISTINCT State
FROM Location
ORDER BY State;

-- 12. Average budget of product where average budget margin > 100
SELECT ProductID, AVG(Budget_Sales) AS AvgBudgetSales,
       AVG(Budget_Margin) AS AvgBudgetMargin
FROM Fact
GROUP BY ProductId
HAVING AVG(Budget_Margin) >= 100;

-- 13. What is the total sales done on date 2010-01-01?
SELECT SUM(Sales) AS TotalSales
FROM Fact
WHERE Date = '2010-01-01';

-- 14. Average total expense of each product ID on an individual date
SELECT Date, ProductID, AVG(Total_Expenses) AS AvgTotalExpenses
FROM Fact
GROUP BY Date, ProductID;

-- 15. Display table with date, product ID, product_type, product, sales, profit, state, area_code
SELECT f.Date, f.ProductID, p.Product_Type, p.Product,
       f.Sales, f.Profit, l.State, f.Area_Code
FROM Fact f
JOIN Product p ON f.ProductID = p.ProductID
JOIN Location l ON f.Area_Code = l.Area_Code;

-- 16. Rank sales without any gap
SELECT ProductID, Sales,
       DENSE_RANK() OVER (ORDER BY Sales DESC) AS SalesRank
FROM Fact;

-- 17. State-wise profit and sales
SELECT l.State, SUM(f.Profit) AS TotalProfit, SUM(f.Sales) AS TotalSales
FROM Fact f
JOIN Location l ON f.Area_Code = l.Area_Code
GROUP BY l.State;

-- 18. State-wise profit and sales with product name
SELECT l.State, p.Product,
       SUM(f.Profit) AS TotalProfit, SUM(f.Sales) AS TotalSales
FROM Fact f
JOIN Location l ON f.Area_Code = l.Area_Code
JOIN Product p ON f.ProductID = p.ProductID
GROUP BY l.State, p.Product;

-- 19. Increased sales after 5% rise
SELECT ProductID, Sales,
       Sales * 1.05 AS IncreasedSales
FROM Fact;

-- 20. Maximum profit along with product ID and product type
SELECT TOP 1 f.ProductID, p.Product_Type, f.Profit
FROM Fact f
JOIN Product p ON f.ProductID = p.ProductID
ORDER BY f.Profit DESC;

-- 21. Stored procedure to fetch result by product type
CREATE PROCEDURE GetProductsByType @ProdType VARCHAR(50)
AS
BEGIN
    SELECT * 
    FROM Product
    WHERE Product_Type = @ProdType;
END;

-- 22. Condition: if total expenses < 60 → Profit else Loss
SELECT ProductID, Total_Expenses,
       CASE WHEN Total_Expenses < 60 THEN 'Profit'
            ELSE 'Loss' END AS Result
FROM Fact;


-- 23. Total weekly sales with roll-up
SELECT DATEPART(WEEK, Date) AS WeekNo, Date, ProductID,
       SUM(Sales) AS WeeklySales
FROM Fact
GROUP BY ROLLUP (DATEPART(WEEK, Date), Date, ProductID);

-- 24. Apply UNION and INTERSECT on area code
SELECT Area_Code FROM FacT
INTERSECT
SELECT Area_Code FROM Location;

SELECT Area_Code FROM Fact
UNION
SELECT Area_Code FROM Location;


-- 25. User-defined function for product type
CREATE FUNCTION GetProductByType(@ProdType VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT * 
    FROM Product
    WHERE Product_Type = @ProdType
);

-- 26.Change product type from coffee to tea where product ID is 1 and undo it
UPDATE Product
SET Product_Type = 'Tea'
WHERE ProductID = 1;

UPDATE Product
SET Product_Type = 'Coffee'
WHERE ProductID = 1;

-- 27. Display date, product ID, and sales where total expenses between 100 and 200
SELECT Date, ProductID, Sales
FROM Fact
WHERE Total_Expenses BETWEEN 100 AND 200;

-- 28. Delete records in ProductTable for regular type
DELETE FROM Product
WHERE Type = 'Regular';
SELECT * FROM Product

-- 29. ASCII value of the 5th character from Product column
SELECT Product, ASCII(SUBSTRING(Product, 5, 1)) AS FifthCharASCII
FROM Product;





















